### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xhwhht** [xmy0916/EuroTruckSelfDriver#4]
Executor requires Program as its Parameter. But you passed in <class 'paddle.fluid.framework.Program'>
就是那句exe.run(fluid.default_startup_program())报错，我把paddle 版本降低还是不行。

**Comment by xmy0916** [comment]
你用的什么版本的paddle？我当时的可能是1.8几的我也记不太清了

**Comment by xhwhht** [comment]
对确实是版本的问题1.8.5不行，后来降到1.8.0可以了。不过新版本是因为什么不太行？

**Comment by xmy0916** [comment]
因为paddle2.0以上是动态图，2.0以下是静态图，差别比较大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月6日(周五) 上午10:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmy0916/EuroTruckSelfDriver] 报错 (#4)




 
对确实是版本的问题1.8.5不行，后来降到1.8.0可以了。不过新版本是因为什么不太行？

**Comment by xhwhht** [comment]
好的，谢谢。

**Comment by xhwhht** [comment]
打扰了，还有几个问题。程序中为啥要用线程来持续运行，而不用一个while循环？这个线程如何退出？

**Comment by xmy0916** [comment]
每个线程里面都有对应的死循环，可以修改下代码根据flag来退出，比如按键q某个标志置1，然后循环中检测这个标志就break。用不同的线程处理主要是因为要保证获取车前视角图像的实时性。 @xhwhht

**Comment by xhwhht** [comment]
好的谢谢
